---
title: "pubpol 543 part 2"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r}
rm(list=ls())

kc_full_long= read.csv("https://github.com/annks10/pubpol543_deliverable3/raw/main/kc_full_long.csv", stringsAsFactors = FALSE)

kc_full_long$percent=(kc_full_long$percent/sum(kc_full_long$percent)*100)
kc_full_long$percent=format(round(kc_full_long$percent,2),nsmall = 2)
kc_full_long$percent=as.numeric(kc_full_long$percent)
str(kc_full_long)

titleText="King County Racial & Ethnic Population Size in 2020"
sourceText="Source: US Census Bureau"
#LABEL=paste0(round(kc_full_long$percent,2),"%")

kc_full_long$variable= factor(kc_full_long$variable, levels = kc_full_long$variable[order(kc_full_long$percent, decreasing = FALSE)])

library(ggplot2)
library(scales)

base=ggplot(data=kc_full_long,
            aes(x=variable, y=percent))
plot1=base+geom_segment( aes(xend=variable, yend=0)) 
plot2=plot1+geom_point( size=4, color="orange") +
  labs(title=titleText,
       x=NULL,
       y=NULL,
       caption = sourceText)
plot3=plot2+scale_y_continuous(breaks=c(0,10,20,30,40,50,60),
                     limits=c(0,60),
                     labels = unit_format(suffix = ""))
plot4=plot3+coord_flip()
plot5=plot4+theme_bw() 
plot6=plot5+theme(plot.caption=element_text(hjust=0),
                  plot.title=element_text(hjust=0.4))

plot7=plot6+geom_text(hjust=0,
                      size=3,
                      aes(y=percent,
                          label=paste0(round(percent,2),"%")))#+coord_flip()
kc_full_longPlot=plot7
kc_full_longPlot
```

```{r}
saveRDS(kc_full_longPlot, file = "kc_full_longPlot")
```


